---
version: "2"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_ROOT_HOST=%
      - TZ=Europe/Stockholm
      - MYSQL_DATABASE=users
      - MYSQL_USER=karin
      - MYSQL_PASSWORD=kpw
    volumes:
      - /opt/webserver_swag/config/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always

  swag:
      image: linuxserver/swag
      container_name: swag
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Stockholm
        - URL=brotjefors.com
        - SUBDOMAINS=
        - VALIDATION=http
        - ACME_DNS_API_TOKEN=alJmamdoYng0M0Facy1aaFhNUV9HQQ==
      volumes:
        - /opt/webserver_swag/config:/config
      ports:
        - 443:443
        - 80:80
      depends_on:
        - mysql
      restart: unless-stopped


  users:
    build: .
    volumes:
      - /opt/webserver_swag/users-0.0.1-SNAPSHOT.jar:/users-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql

